name: Publish  Module - case 3298826

on:
  workflow_dispatch:

jobs:
  publish-module:
    name: Publish Module
    uses: PowerShellLibrary/.github/.github/workflows/publish-module.yml@master
    secrets: inherit
